### ISSUE TITLE
WGSL: Pointer Composite Access

### ISSUE THREAD

**Issue by Kangz** [WebKit/standards-positions#297] opened 2024-01-04 16:24 UTC
### WebKittens

@mwyrzykowski

### Title of the spec

WGSL: Pointer Composite Access

### URL to the spec

https://www.w3.org/TR/WGSL/

### URL to the spec's repository

https://github.com/gpuweb/gpuweb/

### Issue Tracker URL

https://github.com/gpuweb/gpuweb/issues

### Explainer URL

https://github.com/gpuweb/gpuweb/issues/4114

### TAG Design Review URL

N/A

### Mozilla standards-positions issue URL

https://github.com/mozilla/standards-positions/issues/950

### Description

Functionality added to the WebGPU/WGSL spec after its first shipment in a browser. Provides better ergonomics for accessing member of a composite through a pointer. For example `(*ptr).i` can now be written `ptr.i`.

**Comment by mwyrzykowski** [comment] 2024-01-18 00:44
Duplicate of https://github.com/WebKit/standards-positions/issues/107 per earlier discussion

**Closed by mwyrzykowski** 2024-01-18 00:44 UTC
Labels: duplicate, topic: graphics
