### ISSUE TITLE
Web Share Target API

### ISSUE THREAD

**Issue by tomayac** [WebKit/standards-positions#62] opened 2022-09-13 16:35 UTC
## Request for position on an emerging web specification

* WebKittens who can provide input: @marcoscaceres 

### Information about the spec

* Spec Title: Web Share Target API
* Spec URL: https://w3c.github.io/web-share-target/
* GitHub repository: https://github.com/w3c/web-share-target/
* Issue Tracker (if not the repository's issue tracker): https://github.com/w3c/web-share-target/issues/
* Explainer (if not README.md in the repository): https://github.com/w3c/web-share-target/blob/main/docs/explainer.md

### Design reviews and vendor positions

* TAG Design Review: https://github.com/w3ctag/design-reviews/issues/554 (this is for Web Share, not the Web Share Target API)
* Mozilla standards-positions issue: https://mozilla.github.io/standards-positions/#web-share-target

### Bugs tracking this feature

* WebKit Bugzilla: https://bugs.webkit.org/show_bug.cgi?id=194593
* Radar: `<rdar://problem/48080757>`

### Anything else we need to know

This API is supported on Chrome on Android and on Edge on Windows and allows the user to share data (e.g., an image) with apps that register themselves as potential handlers for said data. For example, a funny mustache PWA could register itself as an image handler, so the user can share a selfie they just took to the funny mustache PWA `:-{)`.

**Comment by hortont424** [comment] 2022-09-13 22:39
This is a duplicate of #11

**Closed by hortont424** 2022-09-13 22:39 UTC
Labels: duplicate

**Comment by tomayac** [comment] 2022-09-13 22:45
Oops, sorry for my goldfish brain. I have even commented over there. 🤦‍♂️
