### ISSUE TITLE
WebGPU: Separate Read-only Depth-stencil

### ISSUE THREAD

**Issue by Kangz** [WebKit/standards-positions#295] opened 2024-01-04 16:19 UTC
### WebKittens

@mwyrzykowski

### Title of the spec

WebGPU: Separate Read-only Depth-stencil

### URL to the spec

https://www.w3.org/TR/webgpu/

### URL to the spec's repository

https://github.com/gpuweb/gpuweb/

### Issue Tracker URL

https://github.com/gpuweb/gpuweb/issues

### Explainer URL

https://github.com/gpuweb/gpuweb/issues/3036

### TAG Design Review URL

N/A

### Mozilla standards-positions issue URL

https://github.com/mozilla/standards-positions/issues/953

### Description

Functionality added to the WebGPU/WGSL spec after its first shipment in a browser. Loosens a restriction where using readonly depth-stencil attachments in a render pass required both aspects (depth and stencil) to be readonly. This was too strict, and prevent use-cases where for example the depth is used readonly for contact shadow tracing, while the stencil buffer is written to do identify pixels for further processing. (Both Unity and Unreal do things with mixed depth-stencil readonliness).

**Comment by mwyrzykowski** [comment] 2024-01-18 00:45
Duplicate of https://github.com/WebKit/standards-positions/issues/107 per earlier discussion

**Closed by mwyrzykowski** 2024-01-18 00:45 UTC
Labels: duplicate, topic: graphics
