### ISSUE TITLE
WebGPU default entry points to shader modules

### ISSUE THREAD

**Issue by beaufortfrancois** [WebKit/standards-positions#284] opened 2023-11-23 15:19 UTC
### WebKittens

@mwyrzykowski

### Title of the spec

WebGPU default entry points to shader modules

### URL to the spec

https://gpuweb.github.io/gpuweb/#abstract-opdef-validating-gpuprogrammablestage

### URL to the spec's repository

https://github.com/gpuweb/gpuweb/

### Explainer URL

https://github.com/gpuweb/gpuweb/issues/4342

### Mozilla standards-positions issue URL

https://github.com/mozilla/standards-positions/issues/931

### Description

Default entry points to shader modules have been approved by the GPU for the Web Community Group. See https://github.com/gpuweb/gpuweb/wiki/GPU-Web-2023-11-08#default-entrypoints-to-shader-modules-4342-corentin-is-very-excited-about-this-tiny-addition

**Comment by mwyrzykowski** [comment] 2024-01-18 00:43
Duplicate of https://github.com/WebKit/standards-positions/issues/107 per earlier discussion

**Closed by mwyrzykowski** 2024-01-18 00:43 UTC
Labels: duplicate, topic: graphics
