### ISSUE TITLE
WebGPU: Render to slice of 3D texture

### ISSUE THREAD

**Issue by Kangz** [WebKit/standards-positions#294] opened 2024-01-04 16:16 UTC
### WebKittens

@mwyrzykowski

### Title of the spec

WebGPU: Render to slice of 3D texture

### URL to the spec

https://www.w3.org/TR/webgpu/

### URL to the spec's repository

https://github.com/gpuweb/gpuweb/

### Issue Tracker URL

https://github.com/gpuweb/gpuweb/issues

### Explainer URL

https://github.com/gpuweb/gpuweb/issues/4251

### TAG Design Review URL

N/A

### Mozilla standards-positions issue URL

https://github.com/mozilla/standards-positions/issues/952

### Description

Functionality added to the WebGPU/WGSL spec after its first shipment in a browser. Adds support using a render pass to render to slices of 3D textures in addition to rendering to 2D textures. This is used in graphical algorithm to do voxelization between others.

**Comment by mwyrzykowski** [comment] 2024-01-04 16:37
I asked our web standards engineers and as long as this is being added to the v1 specification, then they didn’t feel separate approvals are needed even though Chrome has already shipped. 

Do you think this process is necessary @Kangz ?

**Comment by Kangz** [comment] 2024-01-04 16:48
Do you mind our referencing this comment instead of opening additional standards-positions in the future? (for small-medium things, larger things like compat we'd still open a standards-position) We still need to reference *something* for WebKit in Chromium's Intent-to-Ship because Mozilla hasn't agreed to the same blanket position for additions to WebGPU v1 (yet).

**Comment by mwyrzykowski** [comment] 2024-01-04 16:49
I don't mind at all. That would be great for us, thank you!

**Comment by mwyrzykowski** [comment] 2024-01-18 00:46
Duplicate of https://github.com/WebKit/standards-positions/issues/107 per earlier discussion

**Closed by mwyrzykowski** 2024-01-18 00:46 UTC
Labels: duplicate, topic: graphics

**Comment by kellyzinnha912-cloud** [comment] 2025-11-16 10:22
> meu lote saldo****
oi alguem
