### ISSUE TITLE
WebGPU: Read-write storage textures

### ISSUE THREAD

**Issue by Kangz** [WebKit/standards-positions#299] opened 2024-01-04 16:26 UTC
### WebKittens

@mwyrzykowski

### Title of the spec

WebGPU: Read-write storage textures

### URL to the spec

https://www.w3.org/TR/webgpu/

### URL to the spec's repository

https://github.com/gpuweb/gpuweb/

### Issue Tracker URL

https://github.com/gpuweb/gpuweb/issues

### Explainer URL

https://github.com/gpuweb/gpuweb/issues/3838

### TAG Design Review URL

N/A

### Mozilla standards-positions issue URL

https://github.com/mozilla/standards-positions/issues/948

### Description

Functionality added to the WebGPU/WGSL spec after its first shipment in a browser. Adds support for (read-only and) read-write storage textures which allow more general access to texture memory for GPU computation and can unlock more advanced graphical algorithms. This feature has been request by developers very often.

**Comment by marcoscaceres** [comment] 2024-01-18 00:24
@mwyrzykowski,  @djg,  @tadeuzagallo, thoughts?

**Comment by mwyrzykowski** [comment] 2024-01-18 00:47
Duplicate of https://github.com/WebKit/standards-positions/issues/107 per earlier discussion

**Closed by mwyrzykowski** 2024-01-18 00:47 UTC
Labels: duplicate, topic: graphics
