### ISSUE TITLE
WGSL: Packed 4x8 Integer Dot Product (DP4)

### ISSUE THREAD

**Issue by Kangz** [WebKit/standards-positions#298] opened 2024-01-04 16:26 UTC
### WebKittens

@mwyrzykowski

### Title of the spec

WGSL: Packed 4x8 Integer Dot Product (DP4)

### URL to the spec

https://www.w3.org/TR/WGSL/

### URL to the spec's repository

https://github.com/gpuweb/gpuweb/

### Issue Tracker URL

https://github.com/gpuweb/gpuweb/issues

### Explainer URL

https://github.com/gpuweb/gpuweb/issues/2677

### TAG Design Review URL

N/A

### Mozilla standards-positions issue URL

https://github.com/mozilla/standards-positions/issues/949

### Description

Functionality added to the WebGPU/WGSL spec after its first shipment in a browser. Adds support new WGSL builtins to work with 4 8-bit numbers packed in a `u32`. The new dot product functionality is especially useful for executing machine learning models that work on 8-bit weights.

**Comment by mwyrzykowski** [comment] 2024-01-18 00:44
Duplicate of https://github.com/WebKit/standards-positions/issues/107 per earlier discussion

**Closed** 2024-01-18 00:47 UTC
Labels: duplicate, topic: graphics
